// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package sqlc

import (
	"database/sql"
)

type Book struct {
	ID           int64         `json:"id"`
	Code         string        `json:"code"`
	FileHash     string        `json:"file_hash"`
	Content      string        `json:"content"`
	FileSize     int64         `json:"file_size"`
	CreatedAt    sql.NullTime  `json:"created_at"`
	LastAccessed sql.NullTime  `json:"last_accessed"`
	AccessCount  sql.NullInt64 `json:"access_count"`
}
