// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package sqlc

import (
	"context"
	"database/sql"
)

const codeExists = `-- name: CodeExists :one
SELECT EXISTS(SELECT 1 FROM books WHERE code = ?) AS exists_flag
`

func (q *Queries) CodeExists(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRowContext(ctx, codeExists, code)
	var exists_flag int64
	err := row.Scan(&exists_flag)
	return exists_flag, err
}

const createBook = `-- name: CreateBook :one
INSERT INTO books (code, file_hash, content, file_size)
VALUES (?, ?, ?, ?)
RETURNING id, code, file_hash, content, file_size, created_at, last_accessed, access_count
`

type CreateBookParams struct {
	Code     string `json:"code"`
	FileHash string `json:"file_hash"`
	Content  string `json:"content"`
	FileSize int64  `json:"file_size"`
}

func (q *Queries) CreateBook(ctx context.Context, arg CreateBookParams) (Book, error) {
	row := q.db.QueryRowContext(ctx, createBook,
		arg.Code,
		arg.FileHash,
		arg.Content,
		arg.FileSize,
	)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FileHash,
		&i.Content,
		&i.FileSize,
		&i.CreatedAt,
		&i.LastAccessed,
		&i.AccessCount,
	)
	return i, err
}

const deleteExpiredBooks = `-- name: DeleteExpiredBooks :execrows
DELETE FROM books WHERE created_at < ?
`

func (q *Queries) DeleteExpiredBooks(ctx context.Context, createdAt sql.NullTime) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteExpiredBooks, createdAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getBookByCode = `-- name: GetBookByCode :one
SELECT id, code, file_hash, content, file_size, created_at, last_accessed, access_count FROM books WHERE code = ? LIMIT 1
`

func (q *Queries) GetBookByCode(ctx context.Context, code string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByCode, code)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FileHash,
		&i.Content,
		&i.FileSize,
		&i.CreatedAt,
		&i.LastAccessed,
		&i.AccessCount,
	)
	return i, err
}

const getBookByHash = `-- name: GetBookByHash :one
SELECT id, code, file_hash, content, file_size, created_at, last_accessed, access_count FROM books WHERE file_hash = ? LIMIT 1
`

func (q *Queries) GetBookByHash(ctx context.Context, fileHash string) (Book, error) {
	row := q.db.QueryRowContext(ctx, getBookByHash, fileHash)
	var i Book
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.FileHash,
		&i.Content,
		&i.FileSize,
		&i.CreatedAt,
		&i.LastAccessed,
		&i.AccessCount,
	)
	return i, err
}

const getBookCount = `-- name: GetBookCount :one
SELECT COUNT(*) FROM books
`

func (q *Queries) GetBookCount(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, getBookCount)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const updateLastAccessed = `-- name: UpdateLastAccessed :exec
UPDATE books
SET last_accessed = CURRENT_TIMESTAMP, access_count = access_count + 1
WHERE code = ?
`

func (q *Queries) UpdateLastAccessed(ctx context.Context, code string) error {
	_, err := q.db.ExecContext(ctx, updateLastAccessed, code)
	return err
}
